# Generated by Django 4.2.7 on 2023-11-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
